import type { Article } from '../articleTypes';

const IMG_EURL_IS =
  'https://images.unsplash.com/photo-1507679799987-c73779587ccf?w=1200&auto=format&fit=crop&q=80';

const CONTENT = [
  `L’**EURL à l’impôt sur les sociétés (IS)** est une société unipersonnelle dont les **bénéfices industriels et commerciaux** (ou non commerciaux selon l’activité) sont imposés au niveau de la **personne morale** selon les **taux et règles d’IS** en vigueur, après déduction des charges et amortissements. Le **dirigeant** se rémunère typiquement par une **rémunération** soumise à cotisations **TNS** ou **assimilées** selon les montages, et par **dividendes** soumis à un régime fiscal spécifique (PFU ou option pour le barème global selon les cas). Ce modèle diffère de l’**EURL à l’IR** où l’**impôt sur le revenu** porte sur le résultat dans le cadre du foyer du dirigeant, avec une logique d’**intégration fiscale** différente.`,
  `**Quand l’EURL à l’IS est-elle pertinente ?** Elle est souvent étudiée lorsque le **niveau de bénéfice** réinvesti dans la société est élevé, lorsque l’**IS** offre un **taux** plus stable ou plus favorable que l’**IR marginal** du dirigeant, ou lorsque l’on souhaite **capitaliser** en société (trésorerie, investissements) avant de distribuer en **dividendes**. Elle est aussi pertinente pour des **projets de croissance** avec **amortissements** importants, **stocks** ou **contrats** longs. La **comparaison** avec la **SASU** (souvent à l’IS également) se fait alors sur la **rémunération** du dirigeant, la **souplesse sociale**, et les **formalités** de gouvernance.`,
  `Les **avantages** de l’EURL à l’IS incluent la **séparation** claire entre le **patrimoine** personnel (sous réserve des engagements) et la **trésorerie** sociétale, la **capacité** à arbitrer entre **réinvestissement** et **distribution**, et l’**imposition** des bénéfices à l’échelon société avec des **règles** connues des investisseurs. Les **charges** déductibles et les **amortissements** réduisent la **base imposable** à l’IS. Pour les **très petites entreprises**, des **réductions** ou **taux** peuvent s’appliquer selon les **seuils** législatifs.`,
  `Les **inconvénients** sont la **complexité** (comptabilité complète, liasse fiscale société, déclarations du dirigeant), la **double fiscalité** potentielle entre **IS** et **taxation des dividendes** (selon le régime), et la **gestion de la trésorerie** pour **payer** l’IS, la **rémunération** et les **acomptes**. La **rémunération** du gérant doit être **cohérente** avec la **rentabilité** : une rémunération trop basse ou trop haute peut poser des **questions** sociales et fiscales.`,
  `Comparée à la **micro-entreprise**, l’EURL à l’IS sort de tout **plafond** de CA et permet une **gestion** fine des **investissements**, mais avec une **charge administrative** bien plus lourde. Comparée au **portage**, elle offre une **autonomie** totale et un **potentiel** de structuration, **sans** statut salarial. Comparée à l’**EURL à l’IR**, elle déplace le **débat fiscal** sur **l’IS** et la **distribution des dividendes** plutôt que sur l’**intégration immédiate** au foyer en IR : **arbitrage** à faire avec un expert.`,
  `Sur le plan **social**, le **gérant** d’EURL n’est pas « salarié » au sens du code du travail de sa propre société ; les **cotisations** et **assiettes** dépendent des **rémunérations** et des **répartitions** de résultat. Les **dividendes** ont un **traitement** fiscal et social distinct des **salaires**. Le simulateur **5 ans** permet de **projeter** des **répartitions** types pour **visualiser** un **net** après IS et prélèvements, **indicativement**.`,
  `La **création** et les **statuts** suivent les mêmes principes que toute **EURL** ; le choix **IR** ou **IS** est une **décision** fiscale structurante, souvent **irréversible** dans un délai sans **friction** : renseignez-vous sur les **options** et **délais** de **révocation**. Une **erreur** d’option peut coûter cher : **conseil expert-comptable** fortement recommandé.`,
  `La **TVA** en EURL à l’IS suit les mêmes règles qu’une **SARL** classique : **réel simplifié** ou **normal** selon les montants et l’activité. Les **stocks** et **créances** sont **suivis** en comptabilité. Les **contrats internationaux** doivent être **analysés** pour la TVA et les **retenues** éventuelles.`,
  `Les **erreurs fréquentes** consistent à **confondre** le **bénéfice comptable** avec la **cash disponible** après IS, à **oublier** les **acomptes d’IS**, ou à **distribuer** des dividendes sans **anticiper** la **trésorerie** et la **taxation**. D’autres dirigeants **négligent** la **rémunération** régulière et se retrouvent en **difficulté** personnelle malgré une **société** rentable.`,
  `Pour le **freelance** en **conseil** ou **IT**, l’EURL à l’IS peut être **pertinente** lorsque le **montant** de marge brute dépasse largement les **besoins** de rémunération immédiate et que le **projet** nécessite de **réinvestir** (recrutement futur, équipements). La **transmission** d’une EURL à l’IS peut être **envisagée** selon les **modalités** de cession de parts.`,
  `En **comparaison** avec la **SASU**, l’**EURL** a un **gérant** unique souvent **très** exposé au **régime TNS** ; la **SASU** offre un **statut** de **président assimilé salarié** avec une **autre** logique de **cotisations** et de **protection sociale**. Le **choix** entre **EURL** et **SASU** n’est **pas** uniquement fiscal : il engage la **gouvernance**, la **représentation** sociale et, parfois, la **levée de fonds**.`,
  `L’**ACRE** et les **exonérations** de début d’activité peuvent s’appliquer dans certains cas : vérifiez les **conditions** de **reprise** et de **cumul**. La **CFE** et les **taxes** locales restent des **charges** à **budgetiser**.`,
  `En **résumé**, l’EURL à l’IS est **pertinente** pour les **indépendants** qui **dépassent** le cadre micro, qui **acceptent** la **complexité** sociétaire, et pour lesquels l’**IS** et le **réinvestissement** dans la société **sont** plus **alignés** avec le **projet** de l’activité que l’**IR** du foyer. Ce n’est **pas** la **meilleure** forme pour tout le monde : **simulez** plusieurs années sur le site, puis **validez** avec un **professionnel**.`,
  `Pour le **référencement** et la **crédibilité**, une **société** à l’IS est **perçue** comme une **structure mature** ; pour les **petits** volumes, **ne** vous **précipitez** pas : une **micro** ou une **EURL IR** peut **suffire**.`,
  `La **veille** sur les **taux d’IS**, les **réductions d’impôt** pour les **PME** et les **règles** de **dividendes** est indispensable. Les **lois de finances 2026** et suivantes peuvent modifier les paramètres utilisés dans le simulateur : mettez à jour vos hypothèses chaque année.`,
  `Les **acomptes d’IS** et le **solde** annuel structurent votre **calendrier de trésorerie** : prévoyez des **réserves** dans la société avant de vous verser une **rémunération** ou des **dividendes** importants. Les **réductions** pour **très petites entreprises** ou **PME** dépendent de **seuils** de chiffre d’affaires et de **capital** : vérifiez les **textes** applicables pour l’exercice concerné. En cas de **revenus** importants côté foyer, l’**arbitrage** entre **IS** et **IR** (via EURL à l’IR) peut être **revisité** régulièrement avec votre conseil.`,
  `Pour un **freelance** en **mission longue** avec **sous-traitance** ou **co-traitance**, l’EURL à l’IS permet de **contractualiser** au nom de la société, de **facturer** la TVA le cas échéant, et de **répartir** la marge entre **rémunération**, **trésorerie** et **investissements** (matériel, recrutement futur). Documentez les **décisions** du gérant (rémunération, distribution) pour **justifier** les flux entre comptes **courants** et **comptes** de **résultat**.`,
  `En **conclusion**, l’EURL à l’IS est un outil de structuration et de croissance pour le freelance qui sort du plafond micro et veut séparer trésorerie personnelle et résultat société. Croisez toujours les résultats du simulateur avec une étude comptable personnalisée : la fiabilité des chiffres dépend des déclarations réelles et des évolutions législatives.`,
].join('\n\n');

export const EURL_IS_ARTICLE: Article = {
  slug: 'eurl-is-freelance-impot-societes-guide-2026',
  title: 'EURL à l’impôt sur les sociétés (IS) : guide freelance 2026',
  excerpt:
    'Comprendre l’EURL à l’IS : réinvestissement, rémunération du gérant, dividendes, comparatif avec EURL IR et SASU, avantages et limites.',
  date: '2026-03-04',
  readingTime: '12 min',
  category: 'EURL',
  imageUrl: IMG_EURL_IS,
  content: CONTENT,
};
