import type { Article } from '../articleTypes';

/** Photo vérifiée (l’ancienne URL Unsplash renvoyait 404) */
const IMG_EURL_IR =
  'https://images.unsplash.com/photo-1552664730-d307ca884978?w=1200&auto=format&fit=crop&q=80';

const CONTENT = [
  `L’**EURL** (entreprise unipersonnelle à responsabilité limitée) est une **société unipersonnelle** : un seul associé qui est en général le **gérant**. Lorsqu’elle est soumise à l’**impôt sur le revenu** (option ou configuration conduisant à l’IR pour les bénéfices industriels et commerciaux / non commerciaux selon l’activité), on parle couramment d’**EURL à l’IR** dans le langage des simulateurs et des consultants. Les **bénéfices** de l’activité sont intégrés dans la **catégorie** correspondante (BIC ou BNC) du foyer du dirigeant, avec les règles d’abattements, de **déduction des charges** et de **cotisations de travailleur non salarié (TNS)** applicables. Ce schéma diffère nettement de l’**EURL à l’IS** où l’impôt sur les sociétés s’applique au niveau de la personne morale.`,
  `**Quand l’EURL à l’IR est-elle pertinente ?** Elle intéresse souvent les **prestataires** qui dépassent les **plafonds de la micro-entreprise**, qui ont besoin de **déduire des charges réelles** importantes (matériel, sous-traitance, locaux, déplacements), ou qui souhaitent une **structure patrimoniale** distincte tout en conservant une logique d’imposition **à l’IR** sur le résultat distribuable. Elle peut convenir lorsque l’on veut **formaliser** une activité avec un **patrimoine professionnel** protégé dans le cadre de la responsabilité limitée sur l’apport, tout en acceptant la **charge comptable** et les **obligations** déclaratives d’une société.`,
  `Les **avantages** incluent la **déduction des charges** professionnelles au réel (comptabilité d’engagement ou de trésorerie selon options), la **clarité** d’un résultat avant impôt distinct, et la **capacité** à emprunter, investir et amortir en nom de société. La forme **SARL/EURL** est **connue** des partenaires et des financeurs. Le gérant majoritaire d’EURL relevant des règles **TNS** pour les cotisations sociales (selon statut précis et rémunérations), avec une logique différente du **président de SASU assimilé salarié**.`,
  `Les **inconvénients** sont la **complexité** accrue : tenue de comptabilité, liasse fiscale, **cotisations sociales** sur rémunérations et résultats selon montage, **coûts** d’expert-comptable et de conformité. L’**imposition à l’IR** peut être **plus lourde** à haut niveau de bénéfices que l’**IS** avec réinvestissement et stratégie de rémunération, selon les taux marginaux du foyer : c’est un **arbitrage** individuel. La **trésorerie** doit absorber les **acomptes d’impôt** et les **échéances sociales**.`,
  `Sur le plan **social**, le **gérant** d’EURL n’est pas salarié de sa société sous les mêmes règles qu’un président de SASU : les **cotisations** passent par les régimes des **indépendants** (assiettes, revenus de travail, dividendes traités selon règles en vigueur). La **rémunération** du gérant et les **dividendes** éventuels modulent le **revenu net** disponible et les **charges**. Le simulateur du site propose des **curseurs** pour certaines répartitions : utilisez-les comme **illustration**, pas comme engagement définitif.`,
  `Comparée à la **micro-entreprise**, l’EURL à l’IR permet de **sortir du plafond** et d’**optimiser** les charges réelles, au prix d’une **structure** plus lourde. Comparée au **portage**, elle offre une **autonomie** totale sur la facturation et la stratégie tarifaire, mais **sans** le statut salarial. Comparée à l’**EURL à l’IS** ou à la **SASU**, elle suit une **logique d’IR** qui peut simplifier ou compliquer la vie selon votre **tranche marginale** et vos **revenus du foyer** (conjoint, propriété, plus-values).`,
  `La **création** d’EURL implique des **statuts**, un **capital**, une **immatriculation**, un **compte bancaire pro** et souvent une **assurance** RC pro selon l’activité. Les **formalités** sont plus longues qu’en micro-entreprise. La **cessation** ou la **vente** de parts nécessite aussi un accompagnement juridique et fiscal pour éviter des **surprises** sur les plus-values ou les **clauses** de cession.`,
  `Pour le **freelance informatique**, **conseil** ou **formation**, l’EURL à l’IR est souvent une **étape** après la micro-entreprise lorsque le **volume** d’affaires et les **charges** le justifient. Les **contrats** avec les clients doivent être signés au nom de la **société** ; la **responsabilité** est en principe **limitée** aux apports, sous réserve des **garanties personnelles** et des fautes de gestion en cas d’abus.`,
  `Les **erreurs fréquentes** consistent à confondre **résultat comptable** et **cash disponible**, à oublier les **provisions** pour l’IR, ou à **mélanger** les comptes perso et pro malgré la société. D’autres dirigeants **négligent** la **rémunération** régulière et se retrouvent avec des **besoins de trésorerie** personnels mal calibrés.`,
  `La **TVA** en EURL dépend du régime choisi (réel simplifié, réel normal, franchise en base si éligibilité selon seuils) : c’est un **paramètre majeur** de trésorerie. Les **déclarations** doivent être **tenues à jour** pour éviter les redressements. L’**export** de prestations hors France pose des questions spécifiques de **place of supply** : renseignez-vous avec un conseiller.`,
  `En **matière d’optimisation**, certaines **charges** (formation, équipement, véhicule selon règles) sont **déductibles** dans des limites précises. Les **indemnités kilométriques** et autres **notes de frais** doivent être **justifiées** et **cohérentes** avec l’activité. Le simulateur **intègre** des paramètres pour **visualiser** des ordres de grandeur de net après IR et cotisations, **sans** remplacer le détail de votre liasse.`,
  `L’**ACRE** et les **exonérations** de début d’activité peuvent s’appliquer dans certains cas : vérifiez les **conditions** de reprise, de **re-création** et de **cumul**. La **CFE** est une charge récurrente à **anticiper** selon les **locaux** et les **communes**.`,
  `L’**EURL à l’IR** peut être **plus pertinente** pour un **foyer** déjà fortement imposé si la **stratégie** de rémunération et de **réinvestissement** dans la société est mieux adaptée qu’une **SASU** dans certains scénarios — inversement pour d’autres profils. La **comparaison** avec **SASU** et **EURL IS** est centrale : le simulateur affiche des **différences de net** sur des hypothèses identiques de TJM et de jours, pour **structurer** la discussion avec votre expert-comptable.`,
  `En **résumé**, l’EURL à l’IR s’adresse aux indépendants qui **dépassent** le cadre micro, qui **valorisent** la déduction de charges et **acceptent** la **complexité** sociétaire. Elle **n’est pas** un « statut magique » : son **intérêt** dépend du **niveau de bénéfice**, du **foyer fiscal**, et des **objectifs** de vie (dividendes, réinvestissement, transmission).`,
  `Pour **améliorer** votre **référencement** et votre **crédibilité**, une **société** peut rassurer certains donneurs d’ordre ; pour d’autres, la **forme** importe moins que la **qualité** de la livraison. Sur le plan **strictement juridique**, respectez les **assemblées** et décisions requises même en **EURL** unipersonnelle lorsque la loi l’impose. Tenez un **registre** des décisions importantes.`,
  `En **transition** depuis la micro-entreprise, anticipez la **cessation** de l’auto-entrepreneur, la **transmission** des contrats, et la **continuité** de facturation. Un **trou de trésorerie** peut survenir si les **clients** paient avec retard pendant la bascule. Prévoyez une **ligne de trésorerie** ou un **coussin** d’épargne.`,
  `Le **respect du droit du travail** et des **missions** en **portage** ou en **micro** n’est pas le même qu’en société : si vous **emploiez** quelqu’un, d’autres **obligations** apparaissent. Pour rester **seul** associé, l’EURL reste adaptée ; pour **associer** des partenaires, d’autres formes peuvent être **privilégiées**.`,
  `En **conclusion**, l’EURL à l’IR est un **outil** de **structuration** pour le freelance **à fort potentiel de charges déductibles** et **dépassant** les plafonds micro. Utilisez le **comparateur** du site sur **plusieurs années** pour intégrer **croissance** et **ACRE**, puis **validez** avec un **expert-comptable** : la **justice** des chiffres dépend des **déclarations réelles** et des **évolutions législatives** de **2026** et au-delà.`,
].join('\n\n');

export const EURL_IR_ARTICLE: Article = {
  slug: 'eurl-ir-freelance-impot-revenu-guide-2026',
  title: 'EURL à l’impôt sur le revenu (IR) : guide freelance 2026',
  excerpt:
    'Comprendre l’EURL à l’IR : TNS, cotisations, déduction des charges, quand ce statut est préférable au micro, au portage ou à l’IS / SASU.',
  date: '2026-03-03',
  readingTime: '12 min',
  category: 'EURL',
  imageUrl: IMG_EURL_IR,
  content: CONTENT,
};
