import type { Article } from '../articleTypes';

const IMG_MICRO =
  'https://images.unsplash.com/photo-1498050108023-c5249f4df085?w=1200&auto=format&fit=crop&q=80';

const CONTENT = [
  `La **micro-entreprise** (régime de la microentreprise, souvent appelé « auto-entrepreneur ») permet d’exercer une activité **indépendante** avec des **formalités allégées** et une **comptabilité simplifiée**. Le revenu est soumis à des **cotisations sociales calculées sur le chiffre d’affaires** (et non sur un bénéfice comptable détaillé comme en régime réel), et l’**impôt sur le revenu** peut être réglé via le **versement libératoire** sous conditions de plafonds de revenus du foyer, ou sinon via une imposition classique avec abattements forfaitaires. Ce régime est encadré par des **plafonds de chiffre d’affaires** : au-delà, le passage à un régime réel ou à une société devient **obligatoire**.`,
  `Pour **2026**, les plafonds de chiffre d’affaires retenus dans la réglementation (et reflétés dans les outils pédagogiques du site) distinguent notamment les activités de **prestations de services** (BNC / BIC de services) des activités de **vente ou assimilées** soumises à des plafonds plus élevés. Ces montants sont **actualisés** par la loi de finances : vérifiez toujours les **valeurs officielles** sur impots.gouv.fr et les communications Urssaf avant toute décision d’investissement. Le simulateur permet de positionner votre activité par rapport à ces plafonds pour anticiper un **changement de régime**.`,
  `**Quand la micro-entreprise est-elle la plus pertinente ?** Elle l’est typiquement lorsque le **chiffre d’affaires prévisionnel reste modéré**, que vous recherchez la **lisibilité** (cotisations proportionnelles au CA encaissé, déclaration simplifiée), et que vous acceptez de ne **pas déduire** les charges professionnelles au réel dans le cadre strict du régime micro (hors régimes mixtes ou exceptions). Elle convient aux **freelances débutants**, aux **activités complémentaires**, et à celles qui veulent **limiter la charge administrative** tout en restant transparents sur leur activité.`,
  `Les **avantages** principaux sont la **rapidité de création**, l’**absence de bilan comptable annuel** au sens des sociétés, la **visibilité** du lien entre CA et cotisations, et souvent une **prise en tête raisonnable** pour un premier pas dans l’entrepreneuriat. La micro-entreprise permet aussi de **tester un marché** avec un coût fixe de structure limité. Pour beaucoup de consultants en **prestation intellectuelle**, le régime offre un bon équilibre entre **temps passé sur la mission** et **temps passé sur l’administratif**.`,
  `Les **inconvénients** sont structurants : les **plafonds** imposent un plafond de développement ; au-delà, vous devez **muter** vers un autre régime. Vous ne bénéficiez **pas** de la déduction des charges au réel dans le cadre micro standard : un consultant avec de **très lourds frais** (matériel, déplacements internationaux, sous-traitance importante) peut parfois être défavorisé par rapport au réel ou à une société — **analyse comptable** indispensable. La **protection sociale** est celle des **TNS** (régime des indépendants), différente du salariat : retraite, invalidité, allocations chômage : renseignez-vous sur les **droits** propres à votre situation. La **TVA** est en principe gérée sous le régime de la **franchise en base** tant que vous y restez éligible ; au-delà des seuils, des obligations supplémentaires apparaissent.`,
  `Sur le plan **fiscal**, le **versement libératoire** peut simplifier la vie lorsqu’il est disponible : il combine impôt et cotisations sur le CA dans une logique forfaitaire, mais des **plafonds de revenu du foyer** peuvent vous en exclure. Sinon, l’imposition se fait avec les **abattements** prévus pour les BIC ou BNC selon votre activité. Le **revenu fiscal de référence** et les **tranches marginales d’imposition** du foyer influencent fortement le **taux effectif** d’IR : le simulateur aide à visualiser des ordres de grandeur, **sans se substituer** à une liasse fiscale personnalisée.`,
  `Comparée au **portage salarial**, la micro-entreprise donne plus de **liberté** et souvent un **potentiel de net** plus élevé pour un même chiffre d’affaires, mais **sans** le filet salarial et avec une **charge mentale** administrative plus grande (déclarations Urssaf, suivi de TVA selon les cas, anticipation de l’IR si pas de libératoire). Comparée à une **EURL** ou une **SASU**, la micro-entreprise évite la **complexité** des bilans et des rémunérations de dirigeant, mais ne permet pas les mêmes **montages** (rémunération, dividende, investissement en société) lorsque l’activité prend de l’ampleur.`,
  `La **gestion du chiffre d’affaires** est au cœur du régime : tout retard ou erreur de déclaration peut générer des **régularisations**. Il est recommandé de **provisionner** l’impôt sur le revenu si vous n’êtes pas au versement libératoire, et de **séparer** les comptes professionnels et personnels pour la lisibilité — même sans comptabilité d’engagement complète. Les **indemnités kilométriques** et autres optimisations visibles dans l’outil doivent être comprises comme des **paramètres de simulation** : en micro, l’impact réel sur votre fiscalité dépend du traitement forfaitaire ou réel selon votre cas.`,
  `Les **erreurs fréquentes** incluent de confondre **CA encaissé** et **facturé** (règles de trésorerie), de négliger le **dépassement de plafond** en fin d’année, ou d’oublier que certaines activités sont **exclues** ou **spécifiques** (réglementation sectorielle). D’autres freelances sous-estiment le coût réel de la **mutuelle** et de la **prévoyance** qu’un salarié aurait en partie couverts différemment.`,
  `La **micro-entreprise** peut être combinée avec une **activité salariée** sous conditions (plafonds cumulés, respect du régime). Ce point est sensible : renseignez-vous sur les règles de **cumul** et sur les obligations déclaratives. De même, le passage progressif vers une **société** doit être anticipé : création d’EURL/SASU, transfert de clientèle, gestion des **stocks** ou des **contrats** en cours.`,
  `Pour le **référencement** et la **crédibilité** commerciale, certains clients préfèrent travailler avec une **société** ; d’autres acceptent volontiers une micro-entreprise pour des missions courtes. Ce n’est pas une règle juridique, mais un **critère commercial**. Votre **TJM** doit intégrer non seulement le net souhaité, mais aussi les **jours non facturés** (prospection, formation, congés).`,
  `En matière de **protection juridique**, l’entrepreneur individuel sous micro-entreprise est **responsable** sur ses biens dans le cadre de l’activité professionnelle selon les règles applicables au patrimoine professionnel ; la **séparation** patrimoine pro / perso a été renforcée par la loi mais ne remplace pas une analyse juridique des contrats. Pour les risques majeurs, la **société** à responsabilité limitée est souvent évoquée comme étape suivante.`,
  `L’**ACRE** (aide à la création) et d’autres dispositifs peuvent réduire temporairement certaines charges : le simulateur **5 ans** permet d’intégrer une hypothèse d’ACRE pour comparer les trajectoires. La **CFE** (cotisation foncière des entreprises) peut s’appliger selon les cas et les exonérations : renseignez-vous auprès de votre service des impôts ou de votre expert-comptable.`,
  `En **conclusion**, la micro-entreprise est un **excellent point d’entrée** et souvent le régime le plus **pertinent** tant que le CA reste compatible avec les **plafonds** et que la **structure de coûts** n’exige pas le réel ou la société. Dès que l’activité se **professionalise** fortement (investissements lourds, recrutement, gros contrats internationaux), comparez systématiquement avec **EURL** et **SASU**. Utilisez le **comparateur** du site sur une base de TJM et de jours cohérente, puis **validez** avec un professionnel : la **justice** d’une simulation dépend entièrement de la **qualité des hypothèses** et des **textes en vigueur** au moment des déclarations.`,
  `Enfin, la **veille réglementaire** est indispensable : les **taux de cotisations**, les **seuils de TVA**, les **plafonds** et les **règles du versement libératoire** évoluent. Les articles publiés sur ce site visent une **information générale** ; pour toute situation litigieuse ou limite de plafond, une **consultation individualisée** reste la seule voie fiable. Le **respect des délais** Urssaf et des **échéances** fiscales évite les majorations et les tensions de trésorerie.`,
  `Sur le plan **international**, les prestations avec des clients hors France soulèvent des questions de **TVA**, de **facturation** et parfois d’**établissement stable** : la micro-entreprise n’immunise pas contre ces règles. Documentez chaque cas. De même, la **sous-traitance** et la **collaboration** avec d’autres freelances doivent être contractuelles pour limiter les litiges.`,
  `La **qualité de vie** du freelance micro-entrepreneur dépend aussi de sa capacité à **industrialiser** ses processus (modèles de devis, suivi de relances, archivage). Moins de paperasse qu’une société ne signifie **pas zéro discipline** : les **justificatifs** utiles en cas de contrôle doivent être conservés selon les durées légales. En combinant **bonne gouvernance** personnelle et **outils de simulation**, vous restez maître de votre trajectoire tout en respectant l’**encadrement légal** du régime.`,
].join('\n\n');

export const MICRO_ARTICLE: Article = {
  slug: 'micro-entreprise-auto-entrepreneur-guide-2026',
  title: 'Micro-entreprise et auto-entrepreneur : guide 2026 (plafonds, avantages, limites)',
  excerpt:
    'Tout savoir sur le régime de la micro-entreprise : plafonds de chiffre d’affaires, cotisations, TVA, versement libératoire, et comparaison avec portage et sociétés.',
  date: '2026-03-02',
  readingTime: '13 min',
  category: 'Micro-entreprise',
  imageUrl: IMG_MICRO,
  content: CONTENT,
};
