import type { Article } from '../articleTypes';

/** Images Unsplash (domaine autorisé dans next.config). Pas de lien mort si l’ID reste valide côté Unsplash */
const IMG_PORTAGE =
  'https://images.unsplash.com/photo-1522071820081-009f0129c71c?w=1200&auto=format&fit=crop&q=80';

const CONTENT = [
  `Le **portage salarial** est une forme d’emploi dans laquelle un salarié exerce une activité de prestation de services pour le compte de clients, tout en étant lié par un **contrat de travail** à une entreprise de portage salarial agréée. Contrairement au travailleur indépendant « classique », le consultant en portage n’est pas à la tête d’une micro-entreprise pour cette mission : il est **salarié** du porteur. Cette différence de nature juridique change tout : protection sociale, fiscalité perçue par le consultant, gestion administrative et niveau de revenu net disponible.`,
  `Sur le plan de l’**activité économique**, le porteur facture les clients, encaisse le chiffre d’affaires et prélève des **frais de gestion** (souvent exprimés en pourcentage du chiffre d’affaires ou forfait selon les offres). Le salaire net versé au consultant correspond au montant facturable diminué de ces frais, des charges sociales patronales et salariales, et éventuellement d’éléments de régularisation. Le simulateur sur ce site modélise ce mécanisme avec un taux de commission paramétrable : c’est un bon ordre de grandeur pour comparer au **micro-entrepreneur** ou à une **société** (EURL, SASU), mais chaque société de portage applique sa grille et ses services.`,
  `**Quand le portage est-il le plus pertinent ?** En pratique, il est souvent choisi au **démarrage** d’une activité de conseil, d’ingénierie, de formation ou d’IT, lorsque l’on souhaite **tester le marché** sans créer immédiatement une structure autonome. Il convient aussi lorsque l’on privilégie la **tranquillité administrative** : pas de déclaration URSSAF en micro-entreprise à gérer soi-même, pas de bilan à produire personnellement comme dirigeant de société. Le portage est également pertinent lorsque l’on veut **préserver une couverture sociale de type salarié** (assurance chômage sous conditions de rechargement ou d’éligibilité, congés payés selon convention et ancienneté) et lorsque les clients exigent une **facturation « pro »** par un intermédiaire reconnu.`,
  `Parmi les **avantages** majeurs figurent la **simplicité de mise en route** (adhésion à un organisme de portage plutôt que formalités complètes de société), la **gestion de la relation contractuelle** avec le client par le porteur, et l’**absence de comptabilité d’entreprise** à tenir en tant qu’indépendant. Le statut salarial peut faciliter l’**accès au crédit immobilier** dans certains profils, car les revenus ressemblent davantage à une fiche de paie stable qu’à un résultat de BIC fluctuant, même si les banques analysent toujours le reste du dossier. Le portage permet enfin de **se concentrer sur la mission** plutôt que sur la prospection purement « entrepreneuriale » de tous les aspects fiscaux.`,
  `Les **inconvénients** sont avant tout **économiques** : le **revenu net** est fréquemment inférieur à ce qu’un micro-entrepreneur ou un dirigeant de société bien optimisé peut retirer pour un même chiffre d’affaires brut, car les frais de gestion et les charges sociales au titre du salariat pèsent sur la masse distribuable. Il y a aussi moins de **liberté organisationnelle** qu’en entreprise individuelle : vous restez dans un cadre de salarié, avec les obligations associées. La **progression du TJM** ne se traduit pas toujours linéairement en net si la structure du porteur ou les minima conventionnels entrent en jeu. Enfin, le portage **n’est pas adapté** à toutes les activités : certaines professions ou montants de facturation poussent vers la société ou la micro-entreprise pour des raisons de plafonds, de TVA ou d’image commerciale.`,
  `Sur le plan de la **TVA et de la facturation**, c’est en général le **porteur** qui facture le client final ; le consultant voit le résultat à travers son salaire et sa fiche de paie. Les règles exactes de TVA, d’exonération ou de franchise dépendent du montage commercial et des choix du porteur : ce point doit être clarifié avec l’organisme, car il n’est pas identique à la gestion de TVA d’un auto-entrepreneur ou d’une société dont vous êtes le seul décideur.`,
  `Comparé à la **micro-entreprise**, le portage simplifie la vie administrative mais **coûte** souvent en net sur le papier pour un même CA, et ne permet pas de « jouer » sur les mêmes leviers de déductions professionnelles que certains régimes réels ou sociétés. Comparé à une **EURL à l’IR** ou à l’**IS** / une **SASU**, le portage évite la complexité de la tenue de comptes annuelle et des décisions de rémunération de dirigeant, mais offre moins de **levier d’optimisation** à long terme pour les très gros volumes de facturation.`,
  `Les **transitions** sont fréquentes : un consultant commence en portage puis bascule en micro ou en société lorsque le volume et la stabilité des missions le justifient. À l’inverse, un indépendant peut rejoindre un portage pour une période donnée si un client ou un marché l’exige. Chaque bascule a des **conséquences fiscales et sociales** : il est indispensable de les anticiper avec un **expert-comptable** et, le cas échéant, avec l’Urssaf ou les organismes compétents.`,
  `Du point de vue du **risque juridique et social**, le portage salarial repose sur des **entreprises agréées** ; l’usage abusif du « faux portage » (disguising de travail dissimulé) est encadré par la loi et les contrôles. Choisir un organisme sérieux, comprendre le contrat de travail et les fiches de paie est essentiel. Pour votre **protection des données** et celle de vos clients, le contrat avec le porteur précise souvent la confidentialité et la propriété intellectuelle des livrables.`,
  `Pour **utiliser le simulateur** efficacement, renseignez un **TJM** et un **nombre de jours facturés** réalistes, ajustez le **taux de frais de gestion** du portage dans les réglages, et comparez le net avec les autres statuts sur la même base de chiffre d’affaires. Vous visualiserez ainsi l’écart entre portage, micro, EURL IR, EURL IS et SASU, en restant conscient que les **hypothèses** (croissance, ACRE, CFE, répartition salaire/dividendes en société) modulent fortement le résultat d’une année sur l’autre.`,
  `En **résumé**, le portage salarial est particulièrement pertinent lorsque la **priorité est la sécurité sociale de type salarié**, la **simplicité** et une **prise en charge administrative** forte, au prix souvent d’un **net inférieur** à d’autres formes d’exercice pour un même volume d’affaires. Il est moins adapté lorsque vous visez l’**optimisation fiscale avancée** ou des **montants très élevés** où la société offre plus de souplesse, sous réserve des obligations comptables et du respect du droit.`,
  `Les **plafonds** propres au régime de la micro-entreprise ou les **règles de TVA** ne s’appliquent pas de la même manière qu’à l’auto-entrepreneur : ne confondez pas les statuts sur la base de simples rumeurs. Les barèmes **URSSAF**, les **taux d’imposition** et les **prélèvements sociaux** évoluent avec les lois de finances : les chiffres présentés dans l’outil pour **2026** visent à refléter les paramètres indicatifs en vigueur pour la simulation, **sans valeur contractuelle**.`,
  `Enfin, pensez à la **durée de votre projet** : une mission de quelques mois ne justifie pas toujours la création d’une société ; le portage peut être le bon compromis. À l’inverse, une activité pérenne avec plusieurs centaines de milliers d’euros de marge brute mérite une **étude comparative** approfondie entre micro, EURL et SASU. Le **tableau comparatif** du site aide à structurer cette réflexion ; la **décision finale** doit intégrer votre situation familiale, vos charges fixes personnelles, votre tolérance au risque et les **conseils d’un professionnel** habilité.`,
  `Les **erreurs fréquentes** consistent à comparer un salaire net de portage à un **revenu de micro-entreprise** sans ramener le chiffre d’affaires au même niveau, ou à oublier les **cotisations** et **impôts** qui s’appliquent dans chaque cas. D’autres consultants surestiment le **bénéfice du chômage** après portage : les règles d’indemnisation dépendent de multiples critères (durée, salaire de référence, motif de fin de contrat). Documentez-vous auprès de France Travail et de votre porteur.`,
  `Sur le plan **commercial**, le portage peut rassurer certains donneurs d’ordre publics ou grands comptes qui préfèrent une **structure intermédiaire** à un auto-entrepreneur isolé (ce n’est pas une règle universelle), mais un critère de choix dans certains marchés. Pour le **prix de vos prestations**, le portage n’empêche pas de négocier un TJM élevé ; c’est la **répartition interne** entre frais, charges et salaire qui détermine votre net.`,
  `La **formation professionnelle** et les **titres professionnels** accessibles en salariat peuvent être un avantage indirect du portage selon les accords de branche ou les politiques du porteur. En micro-entreprise ou en société, la formation est aussi déductible ou financeable autrement : comparez les dispositifs au cas par cas.`,
  `N’oubliez pas la **prévoyance** et les **complémentaires santé** : en salarié, vous êtes souvent couvert par le régime général avec des possibilités de mutuelle collective négociée par le porteur. En indépendant, vous construisez vous-même ces protections. Ce **coût caché** peut expliquer une partie de l’écart de net entre statuts.`,
  `Pour conclure, le portage salarial est un **outil** au service d’un parcours professionnel, pas une fin en soi. Il permet de **lancer une activité** avec un filet de sécurité, de **tester un positionnement tarifaire**, puis de **pivoter** vers un autre statut lorsque les volumes et la maturité de l’entreprise le permettent. Utilisez les **simulations** pour chiffrer, croisez avec un **expert-comptable**, et mettez à jour vos hypothèses chaque année lors des **échéances fiscales** et des **renégociations** avec vos clients.`,
].join('\n\n');

export const PORTAGE_ARTICLE: Article = {
  slug: 'portage-salarial-freelance-guide-complet-2026',
  title: 'Portage salarial : guide complet 2026 (avantages, limites, pertinence)',
  excerpt:
    'Comprendre le portage salarial : statut de salarié, frais de gestion, quand ce statut est le plus adapté, points forts et faiblesses face au micro et aux sociétés.',
  date: '2026-03-01',
  readingTime: '12 min',
  category: 'Portage salarial',
  imageUrl: IMG_PORTAGE,
  content: CONTENT,
};
