import type { Article } from '../articleTypes';

const IMG_SASU =
  'https://images.unsplash.com/photo-1556761175-5973dc0f32e7?w=1200&auto=format&fit=crop&q=80';

const CONTENT = [
  `La **SASU** (société par actions simplifiée unipersonnelle) est une forme juridique très utilisée par les **freelances** et consultants qui veulent une **responsabilité limitée** aux apports, une **image** de structure et une **gouvernance** souple. La société est en principe soumise à l’**impôt sur les sociétés (IS)** sur ses bénéfices après déduction des charges et amortissements. Le **président** est généralement **assimilé salarié** pour la protection sociale : cotisations au **régime général** sur la rémunération, **prélèvement à la source (PAS)**, et obligations de **déclaration** en paie. Les **dividendes** permettent ensuite de distribuer le résultat après IS, avec un régime fiscal distinct (souvent **PFU** ou option pour le barème de l’IR selon conditions).`,
  `**Quand la SASU est-elle la plus pertinente ?** Lorsque le **chiffre d’affaires** et la **marge** dépassent largement le cadre de la micro-entreprise, lorsque l’on vise des **clients** institutionnels ou des **marchés** où la **société** est un critère de **sélection**, lorsque l’on anticipe une **croissance**, une **levée de fonds** ou une **cession** d’actions, ou lorsque la logique **président salarié + IS + dividendes** correspond mieux au projet qu’une **EURL** de gérant **TNS**. La SASU peut aussi convenir lorsque l’on souhaite **séparer** nettement la trésorerie personnelle de celle de la société et **investir** ou **recruter** au nom de la société.`,
  `Les **avantages** majeurs sont la **responsabilité limitée**, la **souplesse** des statuts (possibilité d’évoluer vers plusieurs associés), l’**accès** à une **protection sociale** de type **salarié** pour le président (selon rémunération et règles d’assiette), et la **reconnaissance** du statut de **dirigeant** dans de nombreux secteurs. La SASU facilite parfois les **relations** avec des investisseurs ou des **grands comptes** par rapport à une entreprise individuelle. Les **charges** déductibles et les **amortissements** réduisent la base imposable à l’IS.`,
  `Les **inconvénients** sont la **complexité** (comptabilité complète, liasse fiscale, **DSN**, TVA, déclarations d’IS), les **coûts** de création, d’expert-comptable et de **paie**, et la nécessité de **respecter** les **formalités** (assemblées, décisions, publication des comptes). La **rémunération** et les **dividendes** doivent être **pilotés** : une société **rentable** sur le papier peut laisser le dirigeant **à sec** en liquidités personnelles si la distribution est mal calibrée. La **fiscalité** des dividendes (après IS) s’ajoute à la charge globale : il faut **modéliser** l’ensemble, pas seulement le résultat comptable.`,
  `Comparée à la **micro-entreprise**, la SASU permet de **dépasser** tout plafond de CA et de **structurer** des contrats complexes, **au prix** d’une charge administrative bien plus lourde. Comparée au **portage**, elle offre une **autonomie** totale et un potentiel de net souvent plus élevé dans certains scénarios, sans **statut salarié** du porteur. Comparée à l’**EURL**, la SASU change la **logique sociale** : **assimilé salarié** pour le président (en principe) plutôt que **gérant TNS** — ce n’est **pas** un choix neutre : il dépend des **revenus du foyer**, des **charges personnelles**, des **objectifs** de retraite et de la **répartition** **salaire / dividendes** que vous visez.`,
  `Sur le plan **social**, le président de SASU est en général **affilié au régime général** ; les cotisations portent sur les **rémunérations** versées. Les **dividendes** ne sont pas des salaires : leur **traitement fiscal** et les **prélèvements sociaux** éventuels suivent des règles spécifiques. Le **simulateur** du site permet de poser des **hypothèses** de répartition salaire / dividendes pour **visualiser** des nets **indicatifs** après IS et prélèvements — **sans** valeur contractuelle.`,
  `La **TVA** en SASU est gérée comme pour toute PME : **réel simplifié** ou **normal** selon les seuils et l’activité. Les **obligations** de **facturation électronique** et les **échéances** fiscales doivent être **tenues** pour éviter pénalités et tensions de trésorerie. Les **investissements** professionnels et les **amortissements** influencent la base d’IS et la capacité à distribuer.`,
  `Les **erreurs fréquentes** consistent à **sous-estimer** le coût de la **paie** et des **logiciels** compatibles, à confondre **bénéfice comptable** et **cash disponible** pour le dirigeant, ou à distribuer des dividendes sans anticiper l’IS et la **trésorerie**. D’autres entrepreneurs **négligent** les **délais** de dépôt des comptes ou les **mentions** obligatoires sur les documents commerciaux.`,
  `Pour le freelance **IT** ou **conseil**, la SASU est souvent **pertinente** lorsque le **TJM** et le **volume annuel** justifient la structure et que les **clients** exigent une facturation au nom d’une **société**. Elle peut être **excessive** pour un **petit volume** : comparez avec la **micro** et l’**EURL** sur le **même** chiffre d’affaires **facturé** dans le simulateur.`,
  `La **création** d’une SASU nécessite des **statuts**, un **capital**, une **publication légale**, une **immatriculation** au RCS et un **compte bancaire professionnel**. Les coûts de **conseil** juridique ou **notaire** peuvent s’ajouter si le capital ou les clauses sont complexes. En **transmission**, les **actions** peuvent être cédées selon les **statuts** ; la **valorisation** et la **fiscalité** de cession nécessitent un accompagnement.`,
  `L’**ACRE** et les aides à la création peuvent s’appliquer dans certains cas : vérifiez les **conditions** de reprise d’activité et de **cumul**. La **CFE** et les **taxes locales** doivent être **budgétisées**. La **veille** sur les **taux d’IS**, les **réductions PME** et les **règles** de dividendes est indispensable — les **lois de finances 2026** et suivantes peuvent modifier les **paramètres** du simulateur.`,
  `Pour le **référencement** et la **crédibilité**, des pages **pédagogiques** sur la SASU aident les lecteurs à comprendre **quand** ce statut est adapté ; évitez les affirmations **absolues** : la meilleure forme dépend du **profil**. En **international**, les **prestations** transfrontalières soulèvent des questions de **TVA** et d’**établissement stable** : conseil spécialisé recommandé.`,
  `Les **assemblées générales** et les **décisions** du président doivent être **tracées** lorsque la loi ou les statuts l’exigent : cela sécurise les **cessions** futures et les **contrôles**. Les **comptes annuels** déposés au **greffe** renforcent la **transparence** vis-à-vis des **partenaires** et des **organismes** sociaux.`,
  `Un guide **SEO** sur la SASU doit rappeler que le **président** n’est pas **auto-entrepreneur** : les **obligations** sont celles d’une **PME** à part entière. Les expressions **SASU freelance**, **président assimilé salarié**, **IS**, **dividendes**, **cotisations** peuvent être utilisées **naturellement** dans le fil du texte, sans **bourrage** de mots-clés.`,
  `La **qualité de vie** du dirigeant dépend de la **régularité** de la rémunération, de la **séparation** des comptes et de la **planification** fiscale. Anticipez les **périodes sans mission** avec une réserve de trésorerie. En **résumé**, la SASU est **pertinente** pour le freelance qui a besoin d’une **structure sociétaire complète**, qui accepte la **charge administrative**, et pour qui la logique **président assimilé salarié + IS + dividendes** correspond au projet. Ce n’est pas la seule réponse : utilisez le **comparateur multi-statuts** avec un TJM et des jours cohérents, puis **validez** avec un **expert-comptable**.`,
  `En **conclusion**, la SASU illustre la **structuration** du freelance à fort potentiel. Les chiffres du simulateur sont **indicatifs** et reposent sur les hypothèses **2026** du projet ; seule une **étude individualisée** permet de trancher. Respectez les **délais** fiscaux et sociaux, et **documentez** vos décisions. Pour aller plus loin, croisez avec les **guides** portage, micro, EURL IR et EURL IS sur ce site, et testez le **simulateur 5 ans** avec ACRE et CFE selon votre **éligibilité**. La cohérence entre vos **objectifs personnels** et la **forme juridique** est le levier de réussite.`,
].join('\n\n');

export const SASU_ARTICLE: Article = {
  slug: 'sasu-freelance-president-dividendes-guide-2026',
  title: 'SASU freelance : président, IS, dividendes — guide 2026',
  excerpt:
    'Comprendre la SASU pour indépendants : assimilé salarié, impôt sur les sociétés, répartition salaire et dividendes, avantages par rapport à l’EURL et à la micro.',
  date: '2026-03-05',
  readingTime: '12 min',
  category: 'SASU',
  imageUrl: IMG_SASU,
  content: CONTENT,
};
